"""otimização

Revision ID: 690fe418b11a
Revises: bd3be9097bd7
Create Date: 2025-09-24 20:12:07.417563

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy

# revision identifiers, used by Alembic.
revision: str = '690fe418b11a'
down_revision: Union[str, Sequence[str], None] = 'bd3be9097bd7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.alter_column('events', 'description',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('presences', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('presences', 'event_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('presences', 'match_score',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('user_embeddings', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('user_embeddings', 'embedding',
               existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=512),
               nullable=False)
    op.add_column('users', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(),
               type_=sa.CHAR(length=60),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'hashed_password',
               existing_type=sa.CHAR(length=60),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.drop_column('users', 'updated_at')
    op.alter_column('user_embeddings', 'embedding',
               existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=512),
               nullable=True)
    op.alter_column('user_embeddings', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('presences', 'match_score',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('presences', 'event_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('presences', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('events', 'description',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.drop_column('events', 'updated_at')
    # ### end Alembic commands ###
