"""add cpf

Revision ID: e1096b43110c
Revises: 1884f42277ad
Create Date: 2025-09-25 13:32:24.681024

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e1096b43110c'
down_revision: Union[str, Sequence[str], None] = '1884f42277ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('cpf', sa.String(length=20), nullable=True))
    op.create_index(op.f('ix_users_cpf'), 'users', ['cpf'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_cpf'), table_name='users')
    op.drop_column('users', 'cpf')
    # ### end Alembic commands ###
